// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1bIhIWarX5Fg_AmH3IzGZKwSZbEc0ERI',
    appId: '1:864791754031:web:bd33bb3a1b18811d50ddda',
    messagingSenderId: '864791754031',
    projectId: 'proje2-174aa',
    authDomain: 'proje2-174aa.firebaseapp.com',
    storageBucket: 'proje2-174aa.appspot.com',
    measurementId: 'G-QPXGPBXC3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7yPBhUR-O7a2X79h9Xy8dM_2EabtbqhA',
    appId: '1:864791754031:android:426a83fa28ccae5550ddda',
    messagingSenderId: '864791754031',
    projectId: 'proje2-174aa',
    storageBucket: 'proje2-174aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2BRZuoVN3m_vkVWHdr0cBwFY6Xwy3Xc',
    appId: '1:864791754031:ios:34b877157f97fb3d50ddda',
    messagingSenderId: '864791754031',
    projectId: 'proje2-174aa',
    storageBucket: 'proje2-174aa.appspot.com',
    iosBundleId: 'com.example.deneme6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2BRZuoVN3m_vkVWHdr0cBwFY6Xwy3Xc',
    appId: '1:864791754031:ios:9ae9d6636385252d50ddda',
    messagingSenderId: '864791754031',
    projectId: 'proje2-174aa',
    storageBucket: 'proje2-174aa.appspot.com',
    iosBundleId: 'com.example.deneme6.RunnerTests',
  );
}
